#%RAML 1.0 NamedExample
[
                {
                    flight : {
                      "FlightNumber" : "123",
                      "DepartureDate" : "2002-09-09",
                      "origin" : "malasia",
                      "destination" : 5,
                      "emptyseats" : "12",
                      "departuretime" : "12:00",
                      "ArraivalTime" : "1:00"
                              },
                    "pnr" : [ 
                      "c123",
                      "c124",
                      "c125"
                    ]          

                },
                {
                    flight : {
                      "FlightNumber" : "124",
                      "DepartureDate" : "2002-09-09",
                      "origin" : "malasia",
                      "destination" : 5,
                      "emptyseats" : "12",
                      "departuretime" : "12:00",
                      "ArraivalTime" : "1:00"
                              },
                    "pnr" : [ 
                      "c123",
                      "c124",
                      "c125"
                    ]          

                }
                
                ]